version: '3'
services:
  app:
    build: .
    command: bundle exec unicorn -c /extended-browser-history/config/unicorn.rb
    volumes:
      - .:/extended-browser-history
    ports:
      - "3000:3000"
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    command: nginx -g "daemon off;"
    ports: 
      - "80:80"
    depends_on: 
      - app
    